// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230819030947_MigracionGeneral")]
    partial class MigracionGeneral
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyApi.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("DosisRecomendada")
                        .HasColumnType("longtext");

                    b.Property<string>("FormaAdministracion")
                        .HasColumnType("longtext");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Analgésico y antipirético",
                            DosisRecomendada = "2g de paracetamol",
                            FormaAdministracion = "Solución oral",
                            Indicaciones = "Tomar cada 8 horas durante 10 dias.",
                            Nombre = "Paracetamol"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int?>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especie = " Perro",
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Guarumo",
                            Peso = 12,
                            Raza = "French Poodle"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("longtext");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Propietarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Tapia",
                            CorreoElectronico = "ErikT@Utez",
                            Direccion = "UTEZ",
                            Nombre = "Erik",
                            Telefono = "7772958888"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Costo")
                        .HasColumnType("double");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<double?>("DuracionEstimada")
                        .HasColumnType("double");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("RequisistosPrevios")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 100.0,
                            Descripcion = "Descripcion1",
                            DuracionEstimada = 100.09999999999999,
                            Nombre = "Servicio1",
                            RequisistosPrevios = "Ninguno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
